export { default as Login } from './login';
export { default as Signup } from './signup';
export { default as AddTask } from './addtask';
export { default as TaskList } from './tasklist';
export { default as EditTask } from './edittask';
export { default as TaskDetail } from './taskdetail';
export { default as Analytics } from './analytics';
export { default as Settings } from './settings';
export { default as NotFound } from './notfound';
